src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Twitter_Name__c</fullName>
        <label>Twitter Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Personality_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personality Profiles</relationshipLabel>
        <relationshipName>Personality_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Personality Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personality Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonalityInsightsServiceCont_Test.cls
@isTest
private class PersonalityInsightsServiceCont_Test {
	//https://www.youtube.com/watch?v=nNn-wFbFPL8 
	@testSetup
	static void testDataSetup() {

		Account acc = TestDataFactory.createAccount('Test Account');
		insert acc;

		Contact cont = TestDataFactory.createContact('FirstName', 'LastName', '@TwitterName', acc.Id);
		insert cont;

	}

	@isTest
	static void serviceContr_Success_New_Profile() {

		Contact testContact = [Select Id, FirstName, LastName, Twitter_Name__c From Contact Where FirstName = 'FirstName' Limit 1];

		Test.startTest();
		Personality_Profile__c testpp = PersonalityProfileHelper.getPersonalityInsights(testContact.Id, false);
		Test.stopTest();

		Personality_Profile__c createdProfile = [Select Id From Personality_Profile__c Where Contact__c =: testContact.Id Limit 1];

		System.assert(createdProfile != null, 'PP Created Sucessedfully');

	}

	@isTest static void serviceContr_Success_Update_Exsisting_Profile() {
		//
	}

	@isTest static void serviceContr_Failure_Twitter_API() {
		// Implement test code
	}

	@isTest static void serviceContr_Failure_IBM_Watson_API() {
		// Implement test code
	}

	@isTest static void serviceContr_Failure_Twitter_JSON_Mismatch() {
		// Implement test code
	}

	@isTest static void serviceContr_Failure_IBM_Watson_JSON_Mismatch() {
		// Implement test code
	}

}