src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Twitter_Name__c</fullName>
        <label>Twitter Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Personality_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Agreeableness__c</fullName>
        <label>Agreeableness</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Analysis_Summary__c</fullName>
        <label>Analysis Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Conscientiousness__c</fullName>
        <label>Conscientiousness</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personality Profiles</relationshipLabel>
        <relationshipName>Personality_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraversion__c</fullName>
        <label>Extraversion</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Last_Updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Neuroticism__c</fullName>
        <label>Neuroticism</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Openness__c</fullName>
        <label>Openness</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Personality Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personality Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PersonalityProfileHelper.cls
public class PersonalityProfileHelper {

    @auraEnabled
    public static Personality_Profile__c getPersonalityInsights(String contactId, Boolean isRefresh){
    	PersonalityProfileHelper pp = new PersonalityProfileHelper();
      String twitterHandle = pp.getTwitterHandle(contactId);
    	//System.debug('twitterHandle: '+twitterHandle);
    	if(twitterHandle != null){
        Personality_Profile__c personalityProfile;
        try{
          personalityProfile = pp.getPersonalityProfile(contactId);
        }
        catch(Exception e){
          return null;
        }


        if( personalityProfile != null && !isRefresh){
    			return personalityProfile;
    		}
        else{
					if(isRefresh){
						PersonalityInsightsServiceController ps = new PersonalityInsightsServiceController();
						return ps.getPersonalityInsights(twitterHandle, contactId);
					}else{
						return null;
					}
    		}
    	}
      else{
    		return null;
    	}
    }

    public String getTwitterHandle(String contactId){
    	if(contactId != null){
    		Contact contact = [Select Id, Twitter_Name__c
                            From Contact
                            Where Id =: contactId];

    		return contact.Twitter_Name__c;
    	}
      else{
    		return null;
    	}

    }

    public Personality_Profile__c getPersonalityProfile(String contactId){
    	if(contactId != null){
    		Personality_Profile__c personalityProfile;
    		try{
    			personalityProfile = [Select Id, Last_Updated__c, Contact__c, Agreeableness__c, Analysis_Summary__c, Conscientiousness__c, Extraversion__c, Neuroticism__c, Openness__c
                                  From Personality_Profile__c
                                  Where Contact__c =: contactId];
    		}
        catch(Exception e){
    			return null;
    		}

    		return personalityProfile;
    	}
      else{
    		return null;
    	}

    }
}