src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Twitter_Name__c</fullName>
        <label>Twitter Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Personality_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Agreeableness__c</fullName>
        <label>Agreeableness</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Analysis_Summary__c</fullName>
        <label>Analysis Summary</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Conscientiousness__c</fullName>
        <label>Conscientiousness</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personality Profiles</relationshipLabel>
        <relationshipName>Personality_Profiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Extraversion__c</fullName>
        <label>Extraversion</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Last_Updated__c</fullName>
        <label>Last Updated</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Neuroticism__c</fullName>
        <label>Neuroticism</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Openness__c</fullName>
        <label>Openness</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Twitter</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Personality Profile</label>
    <nameField>
        <displayFormat>PP-{00000}</displayFormat>
        <label>ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personality Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

	public static Account createAccount(String AccountName) {

		Account acc = new Account();
		acc.Name = AccountName;
		return acc;

	}

	public static Contact createContact(String FirstName, String LastName, String TwitterName, Id AccountId ) {

		Contact cont = new Contact();
		cont.AccountId = AccountId;
		cont.FirstName = FirstName;
		cont.LastName = LastName;
		cont.Twitter_Name__c = TwitterName;
		return cont;

	}

 	public static Personality_Profile__c createPersonalityProfile(Id ContactId) {

		Personality_Profile__c pp = new Personality_Profile__c();
		pp.Source__c = 'Source';
		pp.Contact__c = ContactId;
		pp.Analysis_Summary__c = 'Summary';
		pp.Openness__c = 0.80;
		pp.Conscientiousness__c = 0.80;
		pp.Extraversion__c = 0.80;
		pp.Agreeableness__c = 0.80;
		pp.Neuroticism__c = 0.80;
		pp.Last_Updated__c = datetime.now();
		return pp;

	}

}